spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/cloud?characterEncoding=UTF-8&useSSL=false
  jpa:
   show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#配置全局的触发服务降级的超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
#给单个方法配置全局的触发服务降级的超时时间,getProductStockByIdAndRestemp是方法名称
    getProductStockByIdAndRestemp:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
